// Level maps (generated by tools/gen_maps.js, then curated). p = main lane turn points [col,row];
// b = second lane turn points (ends next to the main lane), j = index of the main-lane tile it merges into.
const LEVEL_MAPS = [
  {"p":[[0,1],[6,1],[6,5],[1,5],[1,9],[8,9],[8,12],[5,12]]},  // L1
  {"p":[[2,0],[2,1],[8,1],[8,3],[2,3],[2,5],[5,5],[5,9],[0,9],[0,11],[6,11]]},  // L2
  {"p":[[1,0],[1,3],[7,3],[7,5],[1,5],[1,7],[7,7],[7,9],[1,9],[1,11]]},  // L3
  {"p":[[8,1],[1,1],[1,4],[7,4],[7,6],[1,6],[1,9],[7,9],[7,11]]},  // L4
  {"p":[[1,0],[1,1],[5,1],[5,3],[1,3],[1,5],[4,5],[4,8],[7,8],[7,10],[0,10],[0,12],[6,12]]},  // L5
  {"p":[[2,0],[2,1],[8,1],[8,4],[0,4],[0,6],[3,6],[3,8],[0,8],[0,10],[7,10]]},  // L6
  {"p":[[8,1],[1,1],[1,3],[5,3],[5,7],[1,7],[1,9],[6,9],[6,11]]},  // L7
  {"p":[[5,0],[5,1],[2,1],[2,3],[7,3],[7,7],[1,7],[1,9],[6,9],[6,11]]},  // L8
  {"p":[[0,1],[6,1],[6,3],[1,3],[1,5],[6,5],[6,9],[0,9],[0,11],[6,11]]},  // L9
  {"p":[[1,0],[1,3],[7,3],[7,5],[2,5],[2,8],[8,8],[8,11],[3,11]]},  // L10
  {"p":[[1,0],[1,3],[4,3],[4,1],[7,1],[7,5],[2,5],[2,9],[8,9],[8,11],[4,11]]},  // L11
  {"p":[[8,1],[2,1],[2,5],[7,5],[7,9],[4,9],[4,7],[0,7],[0,11],[5,11]]},  // L12
  {"p":[[6,0],[6,1],[1,1],[1,4],[7,4],[7,7],[1,7],[1,9],[6,9],[6,11]]},  // L13
  {"p":[[0,1],[5,1],[5,3],[8,3],[8,5],[1,5],[1,9],[8,9],[8,11],[5,11]]},  // L14
  {"p":[[1,0],[1,3],[7,3],[7,5],[2,5],[2,7],[8,7],[8,10],[5,10]],"b":[[0,7],[0,11],[3,11],[3,8]],"j":19},  // L15
  {"p":[[1,0],[1,3],[8,3],[8,6],[2,6],[2,9],[7,9],[7,11]]},  // L16
  {"p":[[8,1],[2,1],[2,5],[7,5],[7,7],[4,7],[4,9],[0,9],[0,11],[6,11]]},  // L17
  {"p":[[7,0],[7,1],[1,1],[1,3],[7,3],[7,6],[2,6],[2,8],[5,8],[5,10]],"b":[[0,7],[0,12],[7,12],[7,7]],"j":18},  // L18
  {"p":[[0,1],[6,1],[6,4],[3,4],[3,6],[7,6],[7,10],[0,10],[0,12],[5,12]]},  // L19
  {"p":[[8,3],[4,3],[4,1],[0,1],[0,5],[5,5],[5,7],[8,7],[8,11],[1,11]]},  // L20
  {"p":[[5,0],[5,1],[8,1],[8,3],[2,3],[2,5],[6,5],[6,7],[1,7],[1,11]],"b":[[8,7],[8,12],[4,12],[4,8]],"j":22},  // L21
  {"p":[[0,2],[8,2],[8,5],[3,5],[3,8],[0,8],[0,11],[6,11]]},  // L22
  {"p":[[1,0],[1,1],[7,1],[7,5],[0,5],[0,8],[6,8],[6,12]]},  // L23
  {"p":[[6,0],[6,1],[1,1],[1,3],[7,3],[7,5],[2,5],[2,7],[5,7],[5,10]],"b":[[0,7],[0,12],[7,12],[7,6]],"j":16},  // L24
  {"p":[[8,1],[0,1],[0,5],[6,5],[6,9],[0,9],[0,11],[7,11]]},  // L25
  {"p":[[3,0],[3,1],[8,1],[8,4],[1,4],[1,6],[4,6],[4,9],[8,9],[8,11],[1,11]]},  // L26
  {"p":[[0,0],[3,0],[3,2],[8,2],[8,6],[5,6],[5,9],[8,9],[8,11],[1,11]],"b":[[0,4],[0,9],[2,9],[2,4],[7,4]],"j":12},  // L27
  {"p":[[3,0],[3,1],[0,1],[0,4],[8,4],[8,8],[0,8],[0,11],[7,11]]},  // L28
  {"p":[[1,0],[1,1],[7,1],[7,5],[1,5],[1,7],[8,7],[8,10],[5,10]]},  // L29
  {"p":[[8,1],[1,1],[1,3],[7,3],[7,5],[4,5],[4,7],[7,7],[7,10]],"b":[[0,7],[0,11],[4,11],[4,9],[2,9],[2,4]],"j":10},  // L30
  {"p":[[6,0],[6,1],[0,1],[0,3],[6,3],[6,6],[3,6],[3,9],[0,9],[0,11],[6,11]]},  // L31
  {"p":[[0,1],[6,1],[6,3],[1,3],[1,7],[4,7],[4,9],[0,9],[0,11],[7,11]],"b":[[8,2],[8,8],[5,8]],"j":21},  // L32
  {"p":[[1,0],[1,1],[6,1],[6,3],[3,3],[3,7],[0,7],[0,11],[6,11]],"b":[[8,3],[8,9],[1,9]],"j":20},  // L33
  {"p":[[1,0],[1,1],[7,1],[7,4],[1,4],[1,8],[8,8],[8,10],[2,10]]},  // L34
  {"p":[[8,1],[0,1],[0,3],[3,3],[3,5],[6,5],[6,7],[1,7],[1,11]],"b":[[8,3],[8,10],[7,10],[7,12],[4,12],[4,8]],"j":22},  // L35
  {"p":[[5,0],[5,3],[8,3],[8,7],[4,7],[4,9],[0,9],[0,11],[7,11]],"b":[[1,0],[1,5],[0,5],[0,8]],"j":20},  // L36
  {"p":[[1,0],[1,1],[7,1],[7,4],[2,4],[2,7],[8,7],[8,11],[1,11]],"b":[[0,6],[0,9],[5,9],[5,8]],"j":21},  // L37
  {"p":[[8,1],[2,1],[2,3],[6,3],[6,5],[0,5],[0,7],[3,7],[3,10]],"b":[[8,7],[8,12],[5,12],[5,10],[6,10],[6,6]],"j":14},  // L38
  {"p":[[7,0],[7,3],[4,3],[4,1],[1,1],[1,5],[4,5],[4,7],[8,7],[8,10],[5,10]],"b":[[0,7],[0,12],[3,12],[3,10],[2,10],[2,6]],"j":16},  // L39
  {"p":[[0,3],[3,3],[3,1],[7,1],[7,5],[3,5],[3,7],[8,7],[8,11],[2,11]],"b":[[0,6],[1,6],[1,9],[5,9],[5,8]],"j":21},  // L40
  {"p":[[4,0],[4,1],[7,1],[7,3],[1,3],[1,5],[7,5],[7,9],[1,9],[1,11]]},  // L41
  {"p":[[2,0],[2,1],[5,1],[5,4],[1,4],[1,7],[4,7],[4,9],[1,9],[1,11]],"b":[[8,4],[8,11],[6,11],[6,7],[5,7]],"j":17},  // L42
  {"p":[[8,1],[3,1],[3,3],[0,3],[0,7],[5,7],[5,9],[8,9],[8,11],[1,11]],"b":[[8,7],[7,7],[7,5],[8,5],[8,3],[5,3],[5,6]],"j":19},  // L43
  {"p":[[1,0],[1,3],[7,3],[7,7],[1,7],[1,9],[7,9],[7,11]]},  // L44
  {"p":[[0,0],[7,0],[7,3],[3,3],[3,7],[8,7],[8,11],[2,11]],"b":[[0,3],[0,8],[1,8],[1,9],[7,9]],"j":25},  // L45
  {"p":[[1,0],[1,1],[7,1],[7,3],[1,3],[1,6],[7,6],[7,8],[3,8],[3,12]]},  // L46
  {"p":[[2,0],[2,1],[7,1],[7,4],[0,4],[0,6],[3,6],[3,8],[6,8],[6,10]],"b":[[8,7],[8,12],[0,12],[0,7]],"j":18},  // L47
  {"p":[[8,1],[1,1],[1,3],[7,3],[7,7],[4,7],[4,10]],"b":[[0,6],[1,6],[1,9],[2,9],[2,12],[7,12],[7,8]],"j":19},  // L48
  {"p":[[1,0],[1,2],[7,2],[7,5],[3,5],[3,7],[6,7],[6,9],[0,9],[0,11],[6,11]]},  // L49
  {"p":[[0,0],[5,0],[5,3],[8,3],[8,5],[2,5],[2,7],[7,7],[7,10]],"b":[[0,7],[0,12],[4,12],[4,9],[3,9],[3,8]],"j":22},  // L50
  {"p":[[2,0],[2,1],[8,1],[8,3],[3,3],[3,5],[6,5],[6,7],[0,7],[0,10],[7,10]]},  // L51
  {"p":[[1,0],[1,1],[4,1],[4,5],[0,5],[0,7],[5,7],[5,9],[0,9],[0,11],[4,11]],"b":[[8,2],[6,2],[6,5],[7,5],[7,9],[6,9]],"j":21},  // L52
  {"p":[[0,1],[5,1],[5,3],[8,3],[8,7],[5,7],[5,9],[8,9],[8,12],[1,12]],"b":[[0,4],[0,3],[3,3],[3,7],[0,7],[0,9],[4,9]],"j":19},  // L53
  {"p":[[2,0],[2,1],[7,1],[7,3],[1,3],[1,7],[8,7],[8,11],[1,11]]},  // L54
  {"p":[[2,0],[2,1],[8,1],[8,3],[0,3],[0,7],[4,7],[4,10]],"b":[[8,7],[7,7],[7,12],[0,12],[0,8]],"j":21},  // L55
  {"p":[[8,2],[1,2],[1,5],[5,5],[5,7],[8,7],[8,9],[1,9],[1,12]]},  // L56
  {"p":[[4,0],[4,1],[1,1],[1,3],[7,3],[7,5],[4,5],[4,7],[1,7],[1,11]],"b":[[8,7],[7,7],[7,11],[4,11],[4,10],[3,10],[3,8]],"j":20},  // L57
  {"p":[[0,1],[6,1],[6,3],[2,3],[2,6],[5,6],[5,8],[0,8],[0,11],[3,11]],"b":[[8,3],[8,12],[5,12],[5,9]],"j":20},  // L58
  {"p":[[1,0],[1,1],[6,1],[6,3],[0,3],[0,5],[3,5],[3,7],[8,7],[8,11],[2,11]]},  // L59
  {"p":[[7,0],[7,2],[4,2],[4,0],[1,0],[1,4],[8,4],[8,6],[3,6],[3,10]],"b":[[0,7],[0,9],[1,9],[1,12],[7,12],[7,7]],"j":24},  // L60
  {"p":[[8,1],[0,1],[0,3],[6,3],[6,7],[3,7],[3,9],[0,9],[0,11],[5,11]]},  // L61
  {"p":[[7,0],[7,1],[1,1],[1,3],[7,3],[7,5],[4,5],[4,7],[7,7],[7,11]],"b":[[0,5],[1,5],[1,12],[4,12],[4,8]],"j":22},  // L62
  {"p":[[0,0],[6,0],[6,2],[1,2],[1,4],[7,4],[7,6],[3,6],[3,10]],"b":[[0,7],[0,12],[7,12],[7,7]],"j":23},  // L63
  {"p":[[3,0],[3,1],[0,1],[0,5],[7,5],[7,9],[0,9],[0,11],[7,11]]},  // L64
  {"p":[[6,0],[6,1],[0,1],[0,3],[8,3],[8,5],[4,5],[4,7],[1,7],[1,10]],"b":[[8,7],[8,12],[6,12],[6,11],[5,11],[5,9],[6,9],[6,6]],"j":21},  // L65
  {"p":[[8,1],[1,1],[1,5],[7,5],[7,9],[1,9],[1,11]]},  // L66
  {"p":[[7,0],[7,1],[1,1],[1,3],[7,3],[7,5],[4,5],[4,7],[1,7],[1,11]],"b":[[8,7],[8,11],[3,11],[3,9],[4,9],[4,8]],"j":22},  // L67
  {"p":[[0,1],[7,1],[7,4],[0,4],[0,6],[5,6],[5,10]],"b":[[8,7],[7,7],[7,12],[0,12],[0,7]],"j":19},  // L68
  {"p":[[8,2],[0,2],[0,5],[6,5],[6,9],[0,9],[0,11],[6,11]]},  // L69
  {"p":[[6,0],[6,1],[1,1],[1,3],[4,3],[4,5],[8,5],[8,8],[2,8],[2,10]],"b":[[0,6],[0,12],[7,12],[7,9]],"j":21},  // L70
  {"p":[[0,2],[8,2],[8,6],[1,6],[1,10],[7,10],[7,12]]},  // L71
  {"p":[[1,0],[1,1],[8,1],[8,3],[1,3],[1,5],[4,5],[4,7],[1,7],[1,11]],"b":[[8,6],[7,6],[7,12],[5,12],[5,11],[4,11],[4,8]],"j":24},  // L72
  {"p":[[4,0],[4,1],[7,1],[7,3],[4,3],[4,7],[7,7],[7,9],[0,9],[0,11],[7,11]],"b":[[0,3],[0,0],[2,0],[2,5],[3,5]],"j":11},  // L73
  {"p":[[8,3],[1,3],[1,7],[7,7],[7,11],[4,11],[4,9],[1,9],[1,11]]},  // L74
  {"p":[[4,0],[4,1],[1,1],[1,4],[7,4],[7,6],[2,6],[2,8],[7,8],[7,11]],"b":[[0,6],[0,12],[4,12],[4,10],[3,10],[3,9]],"j":23},  // L75
  {"p":[[0,0],[3,0],[3,2],[7,2],[7,4],[1,4],[1,6],[4,6],[4,8],[8,8],[8,10],[2,10]]},  // L76
  {"p":[[2,0],[2,1],[7,1],[7,3],[1,3],[1,7],[4,7],[4,9],[1,9],[1,11]],"b":[[8,6],[8,11],[6,11],[6,5],[2,5]],"j":16},  // L77
  {"p":[[2,0],[2,1],[8,1],[8,4],[4,4],[4,6],[7,6],[7,10]],"b":[[0,6],[1,6],[1,9],[0,9],[0,12],[4,12],[4,7]],"j":16},  // L78
  {"p":[[8,3],[1,3],[1,7],[8,7],[8,11],[5,11],[5,9],[2,9],[2,11]]},  // L79
  {"p":[[4,0],[4,3],[0,3],[0,6],[6,6],[6,8],[0,8],[0,11],[6,11]],"b":[[8,6],[8,0],[6,0],[6,5]],"j":16},  // L80
];

// Per-level difficulty multipliers, set by bot playtests (tools/calibrate.js)
// v21: levels 20-80 re-set from tools/expert.js (best of 12 bot strategies), a bit under the HP where a good plan still keeps 7 lives
// v22: levels changed by the EMP lasers, Volts, Yetis and electric/ice variants rescaled by (new edge / v21 edge); Volt and Yeti intros (37, 45) x0.85;
//      heavy-shield levels kept at least 10% above the HP where every no-EMP/no-PRISM strategy loses
const LEVEL_CAL = [
  1.65, 1.45, 1.38, 1.23, 1.36, 0.69, 0.66, 0.77, 0.77, 1.21,
  0.77, 0.68, 0.74, 0.69, 0.34, 0.55, 0.52, 0.63, 0.39, 0.79,
  0.16, 0.71, 0.48, 0.46, 0.5, 0.72, 0.34, 0.43, 0.35, 0.46,
  0.76, 0.16, 0.44, 0.22, 0.35, 0.2, 0.52, 0.36, 0.3, 0.38,
  0.37, 0.3, 0.29, 0.35, 0.32, 0.42, 0.26, 0.2, 0.43, 0.32,
  0.41, 0.44, 0.31, 0.4, 0.2, 0.42, 0.22, 0.22, 0.47, 0.35,
  0.33, 0.22, 0.25, 0.32, 0.27, 0.33, 0.14, 0.28, 0.28, 0.34,
  0.28, 0.21, 0.29, 0.36, 0.32, 0.46, 0.35, 0.15, 0.34, 0.34,
];

function seeded(seed) { let s = (seed >>> 0) || 1; return () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296; }
function expandTiles(pts) {
  const out = [pts[0].slice()];
  for (let i = 1; i < pts.length; i++) {
    const [c0, r0] = pts[i - 1], [c1, r1] = pts[i], n = Math.max(Math.abs(c1 - c0), Math.abs(r1 - r0));
    for (let k = 1; k <= n; k++) out.push([c0 + Math.sign(c1 - c0) * k, r0 + Math.sign(r1 - r0) * k]);
  }
  return out;
}
function compressTiles(t) {
  const out = [t[0]];
  for (let i = 1; i < t.length - 1; i++) {
    const a = t[i - 1], b = t[i], c = t[i + 1];
    if (b[0] - a[0] !== c[0] - b[0] || b[1] - a[1] !== c[1] - b[1]) out.push(b);
  }
  out.push(t[t.length - 1]);
  return out;
}

// ---- Wave generator: every level gets its own mix from the enemies unlocked so far ----
const ENEMY_COST = { grunt: 4, scout: 3, splitter: 8, brute: 12, aegis: 14, blink: 8, mender: 12, titan: 30, volt: 10, yeti: 16 };
const ENEMY_GAP  = { grunt: 0.7, scout: 0.4, splitter: 1.1, brute: 1.4, aegis: 0.9, blink: 1.0, mender: 1.6, titan: 3.2, volt: 1.3, yeti: 1.8 };
// special units come in small numbers per group (they change how the fight works, not just its size)
const groupCap = (t, L, cap) => t === 'aegis' ? 1 + Math.floor(L / 15) : t === 'volt' ? 1 + Math.floor(L / 20) : t === 'yeti' ? 1 + Math.floor(L / 30) : cap;

// ---- Shields -----------------------------------------------------------------
// From level 21 every level has shielded enemies. Most are LIGHT: one minor enemy type wears a
// shield, so a shield buster helps but you can get away without one. HEAVY levels (an Aegis dome,
// or shielded types making up a big share of the level's health) get the SHIELDS condition and
// the "heavy shield usage, are you sure?" prompt. The level card badges every shielded enemy.
const HEAVY_SHIELD_SHARE = 0.3;
function shieldPlan(L, noBounty, air) {
  if (L < 12) return null;
  if (L === 12) return { heavy: true, aegis: true, types: 0 };        // Aegis + EMP arrive together
  if (L === 17) return { heavy: false, types: 1 };                    // first light shields (Prism unlocks too)
  const R = seeded(L * 104729 + 77);
  const pHeavy = noBounty || air ? (L > 40 ? 0.25 : 0) : L >= 21 ? 0.4 : 0.45;
  if (R() < pHeavy) {
    if (L < 17 || R() < 0.5) return { heavy: true, aegis: true, types: L >= 30 ? 1 : 0 };
    return { heavy: true, aegis: false, types: L >= 40 ? 2 : 1 };
  }
  if (L >= 21 || R() < 0.3) return { heavy: false, types: 1 };
  return null;
}
// share of the level's ground-enemy health that each type brings
function typeShares(waves) {
  const hp = {}; let tot = 0;
  waves.forEach((g, w) => g.forEach(([t, n]) => {
    if (ENEMIES[t].flying) return;
    const v = n * ENEMIES[t].hp * (1 + 0.07 * w); hp[t] = (hp[t] || 0) + v; tot += v;
  }));
  for (const t in hp) hp[t] /= tot || 1;
  return hp;
}
function pickShieldTypes(L, waves, plan, calmStart) {
  if (!plan || !plan.types) return [];
  const R = seeded(L * 31337 + 5), share = typeShares(waves);
  // No Bounty levels keep the opening shield-free so Mints have time to pay off
  const early = new Set(calmStart ? waves.slice(0, 2).flatMap(g => g.map(x => x[0])) : []);
  const ok = t => t !== 'aegis' && t !== 'mite' && !early.has(t) && (t !== 'boss' || (plan.heavy && L >= 50));
  let c = Object.keys(share).filter(ok);
  const out = [];
  const take = (list, weight) => { let x = R() * list.reduce((a, t) => a + weight(t), 0); for (const t of list) { x -= weight(t); if (x <= 0) return t; } return list[list.length - 1]; };
  if (!plan.heavy) {                       // light: a minor type, never more than a small slice of the level
    let minor = c.filter(t => share[t] >= 0.05 && share[t] <= 0.2);          // noticeable, but not a big slice
    if (!minor.length) minor = c.filter(t => share[t] <= 0.2);
    if (!minor.length) return [];
    out.push(take(minor, () => 1));
    return out;
  }
  while (out.length < plan.types && c.length) { const t = take(c, t => share[t]); out.push(t); c = c.filter(x => x !== t); }
  // a heavy level without an Aegis must really be heavy: keep adding the biggest types until it is
  while (!plan.aegis && c.length && out.length < 3 && out.reduce((a, t) => a + share[t], 0) < HEAVY_SHIELD_SHARE) {
    const t = c.sort((a, b) => share[b] - share[a])[0]; out.push(t); c = c.filter(x => x !== t);
  }
  return out;
}

function makeWaves(L, twoLanes, air, plan) {
  const R = seeded(L * 7919 + 13);
  const boss = L % LEVELS_PER_WORLD === 0;
  const n = L <= 2 ? 5 : L <= 9 ? 6 : L <= 19 ? 7 : 8;
  const pool = ENEMY_ORDER.filter(k => k !== 'boss' && !ENEMIES[k].flying && ENEMIES[k].intro <= L && (k !== 'aegis' || (plan && plan.aegis)));
  const fresh = pool.find(k => ENEMIES[k].intro === L);
  const pickWeighted = (exclude) => {
    const c = pool.filter(k => !exclude.includes(k));
    if (!c.length) return null;
    const ws = c.map(k => (1 + 2 * ENEMIES[k].intro / L) * (ENEMIES[k].elec || ENEMIES[k].ice ? 0.5 : 1));   // Volts and Yetis: special, so rarer
    let x = R() * ws.reduce((a, b) => a + b, 0);
    for (let i = 0; i < c.length; i++) { x -= ws[i]; if (x <= 0) return c[i]; }
    return c[c.length - 1];
  };
  // v21: from level 20 the crowd grows: more enemies per wave (x1.35 by level 40, x1.6 by 80),
  // spawned closer together so levels get denser rather than much longer
  const crowd = L < 20 ? 1 : 1 + 0.35 * Math.min(1, (L - 20) / 20) + 0.25 * Math.max(0, (L - 40) / 40);
  const cap = L < 20 ? 30 : 36;
  const waves = [];
  for (let w = 1; w <= n; w++) {
    // counts grow until level 40, then mostly toughness grows (keeps levels short and fair)
    const fullBudget = crowd * (22 + Math.min(L, 40) * 1.4 + Math.max(0, L - 40) * 0.35) * (1 + 0.28 * (w - 1));
    const budget = air ? fullBudget * 0.72 : fullBudget;     // on Air Raid levels over a quarter of each wave flies
    const types = [];
    if (w === 1) types.push(fresh === 'scout' ? 'scout' : 'grunt');
    else {
      const k = L < 4 ? (R() < 0.5 ? 1 : 2) : (R() < 0.45 ? 2 : 3);
      if (fresh && fresh !== 'grunt') types.push(fresh);
      while (types.length < Math.min(k, pool.length)) { const t = pickWeighted(types); if (!t) break; types.push(t); }
      // an Aegis level always has Aegis in wave 3 and every other wave after it
      if (plan && plan.aegis && w >= 3 && (w % 2 === 1 || w === n) && !types.includes('aegis')) {
        if (types.length >= 2) types[types.length - 1] = 'aegis'; else types.push('aegis');
      }
    }
    const groups = types.map((t, i) => {
      const count = Math.max(1, Math.min(groupCap(t, L, cap), Math.round(budget / types.length / ENEMY_COST[t])));
      const gap = +(ENEMY_GAP[t] * (0.85 + R() * 0.3) * Math.max(L <= 40 ? 0.55 : 0.5, 1 - 0.012 * (L - 1)) / crowd ** 0.7).toFixed(2);
      return [t, count, gap, twoLanes ? (types.length === 1 ? -1 : i % 2) : 0];
    });
    if (air) groups.push(['glider', Math.max(2, Math.round(fullBudget * 0.28 / 5)), +(0.9 * Math.max(0.5, 1 - 0.01 * (L - 1))).toFixed(2), twoLanes ? -1 : 0]);
    if (boss && w === n) groups.push(['boss', L >= 80 ? 3 : L >= 40 ? 2 : 1, 6, twoLanes ? -1 : 0]);
    waves.push(groups);
  }
  return waves;
}

const levelHp = L => 1 + 0.035 * (L - 1);

// Every lane must run along the grid. If a segment is ever diagonal, bend it into an L.
function gridSafe(pts) {
  const out = [pts[0]];
  for (let i = 1; i < pts.length; i++) {
    const a = out[out.length - 1], b = pts[i];
    if (a[0] !== b[0] && a[1] !== b[1]) out.push([b[0], a[1]]);
    out.push(b);
  }
  return out;
}
const LEVELS = LEVEL_MAPS.map((m, i) => {
  const n = i + 1;
  const main = expandTiles(m.p);
  const paths = [m.p];
  const lanes = [m.p];
  if (m.b) {
    const bt = expandTiles(m.b);
    paths.push(gridSafe(compressTiles(bt.concat(main.slice(m.j)))));
    lanes.push(gridSafe(compressTiles(bt.concat([main[m.j]]))));
  }
  const boss = n % LEVELS_PER_WORLD === 0;
  const noBounty = NO_BOUNTY_LEVELS.includes(n), air = AIR_LEVELS.includes(n);
  const plan = shieldPlan(n, noBounty, air);
  return {
    n, world: Math.min(THEMES.length - 1, Math.floor(i / LEVELS_PER_WORLD)), paths, lanes, boss,
    waves: makeWaves(n, !!m.b, air, plan), noBounty, air, shielded: false, plan, shieldTypes: [],
    gold: Math.round((140 + 4 * n + (boss ? 40 : 0)) * (noBounty ? 1.15 : 1)),
    newTower: TOWER_ORDER.find(t => TOWERS[t].unlock === n) || null,
    newEnemy: ENEMY_ORDER.find(k => ENEMIES[k].intro === n) || null,
    twoPortals: !!m.b && !LEVEL_MAPS.slice(0, i).some(x => x.b),
    hp: w => levelHp(n) * (1 + 0.07 * (w - 1)) * LEVEL_CAL[i],
  };
});
// No Bounty levels get a calm opening: no Aegis in wave 2, so Mints have time to pay off before shields arrive
for (const lv of LEVELS) if (lv.noBounty && lv.waves[1])
  lv.waves[1] = lv.waves[1].map(g => g[0] === 'aegis' ? ['grunt', Math.min(30, Math.round(g[1] * ENEMY_COST.aegis / ENEMY_COST.grunt)), ENEMY_GAP.grunt * g[2] / ENEMY_GAP.aegis, g[3]] : g);
for (const lv of LEVELS) {
  lv.shieldTypes = pickShieldTypes(lv.n, lv.waves, lv.plan, lv.noBounty);
  lv.hasAegis = lv.waves.some(g => g.some(x => x[0] === 'aegis'));
  const sh = typeShares(lv.waves);
  lv.shieldShare = lv.shieldTypes.reduce((a, t) => a + (sh[t] || 0), 0);
  lv.hasShields = lv.hasAegis || lv.shieldTypes.length > 0;
  lv.shielded = lv.hasAegis || lv.shieldShare >= HEAVY_SHIELD_SHARE;     // HEAVY: condition + prompt
}
// ---- Electric and ice variants: on some levels one minor enemy type is electrified or iced ----
// Electrified from level 39, iced from level 47, on about a third of levels (more after 60).
// Bigger, rarer types are preferred so a variant is a few special enemies, not a whole swarm.
function variantTypes(L, waves, taken, kind) {
  if (L < (kind === 'elec' ? 39 : 47)) return [];
  const R = seeded(Math.imul(L + (kind === 'elec' ? 101 : 707), 2654435761) ^ 0x5bd1e995);
  R(); R();                                     // (a well-mixed seed, so neighbouring levels don't all roll the same)
  if (R() >= (L < 60 ? 0.35 : 0.45)) return [];
  const share = typeShares(waves);
  let c = Object.keys(share).filter(t => !['aegis', 'mite', 'boss'].concat(kind === 'elec' ? ['titan'] : []).includes(t) && !taken.includes(t) && !ENEMIES[t].elec && !ENEMIES[t].ice && share[t] >= 0.04 && share[t] <= 0.3);
  const big = c.filter(t => ENEMY_COST[t] >= 8);
  if (big.length) c = big;
  return c.length ? [c[Math.floor(R() * c.length)]] : [];
}
for (const lv of LEVELS) {
  lv.elecTypes = variantTypes(lv.n, lv.waves, lv.shieldTypes, 'elec');
  lv.iceTypes = variantTypes(lv.n, lv.waves, lv.shieldTypes.concat(lv.elecTypes), 'ice');
  const has = k => lv.waves.some(g => g.some(x => ENEMIES[x[0]][k]));
  lv.hasElec = lv.elecTypes.length > 0 || has('elec');
  lv.hasIce = lv.iceTypes.length > 0 || has('ice');
}
function levelEnemies(lv) {
  const set = new Set();
  lv.waves.forEach(g => g.forEach(x => { set.add(x[0]); if (ENEMIES[x[0]].split) set.add(ENEMIES[x[0]].split.type); }));
  return ENEMY_ORDER.concat(['mite']).filter(k => set.has(k));
}
